tailwind.config = {
    darkMode: "class",
    theme: {
        extend: {
            "colors": {
                "on-primary-container": "#5c2800",
                "surface-variant": "#e9e1dc",
                "on-primary": "#ffffff",
                "tertiary-fixed": "#ffdad8",
                "surface-bright": "#fff8f5",
                "on-surface": "#1e1b18",
                "primary-container": "#ff7a00",
                "secondary": "#765b00",
                "tertiary-fixed-dim": "#ffb3b1",
                "error": "#ba1a1a",
                "on-tertiary-container": "#750015",
                "on-secondary": "#ffffff",
                "surface-container-low": "#fbf2ed",
                "on-background": "#1e1b18",
                "on-primary-fixed-variant": "#753400",
                "primary": "#994700",
                "on-error-container": "#93000a",
                "secondary-container": "#ffc703",
                "surface-dim": "#e1d8d4",
                "on-secondary-container": "#6e5400",
                "on-secondary-fixed": "#251a00",
                "secondary-fixed": "#ffdf94",
                "on-secondary-fixed-variant": "#594400",
                "on-tertiary": "#ffffff",
                "error-container": "#ffdad6",
                "inverse-primary": "#ffb68b",
                "on-primary-fixed": "#321200",
                "background": "#fff8f5",
                "surface-container": "#f5ece7",
                "outline-variant": "#e0c0af",
                "outline": "#8c7263",
                "surface-container-lowest": "#ffffff",
                "on-error": "#ffffff",
                "inverse-on-surface": "#f8efea",
                "inverse-surface": "#34302c",
                "primary-fixed": "#ffdbc8",
                "tertiary": "#bb152c",
                "on-surface-variant": "#584235",
                "tertiary-container": "#ff7576",
                "secondary-fixed-dim": "#f5bf00",
                "surface-container-high": "#efe6e2",
                "primary-fixed-dim": "#ffb68b",
                "surface": "#fff8f5",
                "surface-tint": "#994700",
                "on-tertiary-fixed-variant": "#92001c",
                "surface-container-highest": "#e9e1dc",
                "on-tertiary-fixed": "#410007"
            },
            "borderRadius": {
                "DEFAULT": "0.25rem",
                "lg": "0.5rem",
                "xl": "0.75rem",
                "full": "9999px"
            },
            "spacing": {
                "margin-desktop": "40px",
                "stack-md": "24px",
                "gutter": "24px",
                "base": "8px",
                "stack-sm": "12px",
                "stack-lg": "48px",
                "container-max": "1280px",
                "margin-mobile": "16px"
            },
            "fontFamily": {
                "label-md": ["Be Vietnam Pro"],
                "body-lg": ["Be Vietnam Pro"],
                "headline-lg": ["Quicksand"],
                "headline-lg-mobile": ["Quicksand"],
                "headline-md": ["Quicksand"],
                "display-lg": ["Quicksand"],
                "label-sm": ["Be Vietnam Pro"],
                "body-md": ["Be Vietnam Pro"]
            },
            "fontSize": {
                "label-md": ["14px", {"lineHeight": "20px", "letterSpacing": "0.01em", "fontWeight": "600"}],
                "body-lg": ["18px", {"lineHeight": "28px", "fontWeight": "400"}],
                "headline-lg": ["32px", {"lineHeight": "40px", "fontWeight": "700"}],
                "headline-lg-mobile": ["28px", {"lineHeight": "36px", "fontWeight": "700"}],
                "headline-md": ["24px", {"lineHeight": "32px", "fontWeight": "600"}],
                "display-lg": ["48px", {"lineHeight": "56px", "letterSpacing": "-0.02em", "fontWeight": "700"}],
                "label-sm": ["12px", {"lineHeight": "16px", "fontWeight": "700"}],
                "body-md": ["16px", {"lineHeight": "24px", "fontWeight": "400"}]
            }
        },
    },
};